export const getAntTheme = (themeColor) => ({
  fontSize: 16,
  lineWidth: 1,
  lineHeight: 1.5,
  colorBgLayout: themeColor.White,
  fontFamily: "'Inter', sans-serif",
  colorLink: themeColor.PrimaryLight,
  colorText: themeColor.TextSecondary,
  colorBorder: themeColor.BorderColor,
  colorBgContainer: themeColor.BgWhite,
  colorBorderSecondary: themeColor.BorderColor,
});

export const getAntComponent = (themeColor) => ({
  Button: {
    lineWidth: 1,
    borderRadius: 10,
    colorBorder: themeColor.Primary,
    controlHeight: 40,
    controlHeightLG: 48,
    controlHeightSM: 32,
    colorText: themeColor.Primary,
    colorPrimary: themeColor.Primary,
    colorLink: themeColor.Primary,
    colorPrimaryBg: themeColor.Primary,
    colorPrimaryBgHover: themeColor.Primary,
    colorPrimaryHover: themeColor.Primary,
    colorPrimaryActive: themeColor.Primary,
    fontWeightStrong: 500,
  },
  Menu: {
    itemSelectedBg: themeColor.SelectBg,
    itemSelectedColor: themeColor.Primary,
  },
  Layout: {
    colorBgLayout: themeColor.White,
    colorBgHeader: themeColor.White,
  },
  Header: {
    controlHeight: 72,
  },
  Input: {
    lineWidth: 1,
    fontSize: 16,
    borderRadius: 4,
    controlHeightSM: 32,
    controlHeightLG: 48,
    controlHeight: 40,
    colorBorder: themeColor.Dark4,
    colorBgBase: themeColor.White,
    colorText: themeColor.InputText,
    colorTextPlaceholder: themeColor.TextSecondary,
    colorPrimaryHover: themeColor.Primary,
  },
  Select: {
    fontSize: 16,
    fontSizeLG: 16,
    lineWidth: 1,
    borderRadius: 6,
    controlHeightSM: 60,
    controlHeightLG: 72,
    controlHeightXS: 40,
    colorText: themeColor.TextPrimary,
    colorPrimaryHover: themeColor.Primary,
    colorBorder: themeColor.BorderColor,
    colorTextPlaceholder: themeColor.TextSecondary,
    controlItemBgHover: themeColor.TextColor,
  },
  Option: {
    controlHeightLG: 32,
  },
  Tag: {
    fontSize: 13,
    fontSizeSM: 13,
    lineWidth: 0,
    borderRadiusSM: 40,
    colorText: themeColor.TextSecondary,
    lineHeight: 1.21,
    colorFillAlter: themeColor.TextColor,
    colorBorder: themeColor.BorderColor,
    paddingSM: 16,
    fontWeightStrong: 500,
  },
  Checkbox: {
    colorText: themeColor.TextPrimary,
    colorPrimaryBg: themeColor.Primary,
    colorPrimaryHover: themeColor.Primary,
    colorPrimaryActive: themeColor.Primary,
    lineHeight: 1,
    controlInteractiveSize: 24,
    colorPrimary: themeColor.Primary,
  },
  Typography: {
    fontSizeSM: 14,
    fontSizeLG: 16,
    margin: 0,
    fontFamily: "'Epilogue', sans-serif",
    fontSizeHeading1: 36,
    fontSizeHeading2: 24,
    fontSizeHeading3: 18,
    fontSizeHeading4: 16,
    fontSizeHeading5: 14,
    lineHeightHeading1: 1.091,
    lineHeightHeading2: 1.1,
    lineHeightHeading3: 1.25,
    lineHeightHeading4: 1.4,
    lineHeightHeading5: 1.5,
    lineWidthBold: 1,
    colorText: themeColor.TextSecondary,
    colorLink: themeColor.TextSecondary,
    colorTextHeading: themeColor.TextPrimary,
    fontWeightStrong: 700,
  },
  Card: {
    colorText: themeColor.TextSecondary,
    colorLink: themeColor.PrimaryLight,
    colorTextHeading: themeColor.TextPrimary,
    borderRadius: 4,
    lineWidth: 1,
    lineType: "solid",
    paddingLG: 0,
    borderRadiusLG: 12,
    borderRadiusOuter: 12,
    fontSizeSM: 14,
    fontSizeLG: 16,
    colorBorder: themeColor.BorderColor,
    colorBgBase: themeColor.White,
    colorBorderSecondary: themeColor.TextColor,
    colorBgContainer: themeColor.White,
    boxShadowSecondary: "0px 4px 4px 1px rgba(0, 0, 0, 0.04)",
    boxShadow: "0px 4px 4px 1px rgba(0, 0, 0, 0.04)",
  },
  List: {
    colorBgBase: themeColor.BgWhite,
  },
  Divider: {
    marginLG: 0,
    colorBorder: themeColor.BorderColor,
    colorFillAlter: themeColor.BorderColor,
  },
  Badge: {
    colorText: themeColor.White,
  },
  Collapse: {
    colorFillAlter: themeColor.White,
  },
  Link: {
    colorText: themeColor.Primary,
  },
  Avatar: {
    lineWidth: 0,
    boxShadow: "0px 4px 4px rgba(0, 0, 0, 0.04)",
  },
});
